image: python:3.7

stages:
  # - test
  # - lint
  # - types
  - build
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry version $(git describe --tags --abbrev=0)
  - poetry install
  # - pip list

# Unit Tests:
#   stage: test
#   script:
#     - poetry run pytest

# Python Code Lint:
#   stage: lint
#   script:
#     - poetry run black .

# Static Type check:
#   stage: types
#   script:
#     - poetry run mypy .

build:
  stage: build
  artifacts:
    paths:
      - dist
  script:
    - poetry build

deploy:
  stage: deploy
  script:
    - pip install twine
    - twine upload --repository-url $PYPI_REPOSITORY -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*.whl
  rules:
    - if: $CI_COMMIT_TAG