default:
  image: python:3.7
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry version $(git describe --tags --abbrev=0)
    - poetry install
  tags:
    - linux
    - docker

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist
  script:
    - poetry build

deploy:
  stage: deploy
  script:
    - pip install twine
    - twine upload --repository-url $PYPI_REPOSITORY -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*.whl
  rules:
    - if: $CI_COMMIT_TAG
