default:
  image: python:3.7
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry version $(git describe --tags --abbrev=0)
    - poetry install
  tags:
    - linux
    - docker

stages:
  - build

build:
  stage: build
  artifacts:
    paths:
      - dist
  script:
    - poetry build
